export const ON_LOGIN_BTN_CLICK='ON_LOGIN_BTN_CLICK';
export const ON_LOGIN_BTN_CLICK_SUCCESS='ON_LOGIN_BTN_CLICK_SUCCESS';
export const ON_LOGIN_BTN_CLICK_ERROR='ON_LOGIN_BTN_CLICK_ERROR';




//任务列表
export const ON_HTTP_TASKLIST_INIT = 'ON_TASKLIST_INIT';
export const ON_WEBSOCKET_TASKLIST_UPDATE = 'ON_WEBSOCKET_TASKLIST_UPDATE';
export const ON_WEBSOCKET_TASKLIST_DELETE = 'ON_WEBSOCKET_TASKLIST_DELETE';
export const ON_WEBSOCKET_TASKLIST_ADD = 'ON_WEBSOCKET_TASKLIST_ADD';

//任务详情
export const ON_WEBSOCKET_GET_OILMESS='ON_WEBSOCKET_GET_OILMESS';//接受websocket传来的实时加油量

//获取油料参数
export const ON_HTTP_GET_OIL_INFORMATION = 'ON_HTTP_GET_OIL_INFORMATION';

//修改按钮状态指示
export const ON_CHANGE_TASK_INFORMATION_BUTTON_STATE = 'ON_CHANGE_TASK_INFORMATION_BUTTON_STATE';